# טעינת סיפריות ודאטה

In [ ]:
!pip uninstall -y numpy scipy gensim
!pip install --no-cache-dir "numpy==1.26.4" "scipy==1.11.4" "gensim==4.3.2"


Found existing installation: numpy 1.26.4
Uninstalling numpy-1.26.4:
  Successfully uninstalled numpy-1.26.4
Found existing installation: scipy 1.11.4
Uninstalling scipy-1.11.4:
  Successfully uninstalled scipy-1.11.4
Found existing installation: gensim 4.3.2
Uninstalling gensim-4.3.2:
  Successfully uninstalled gensim-4.3.2
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 83.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.4/60.4 kB 8.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 63.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 36.4/36.4 MB 190.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.7/26.7 MB 172.2 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26

In [ ]:
# NLP
import pandas as pd
import numpy as np
from gensim.models import Word2Vec

In [ ]:
# Feature Extraction
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer


In [ ]:
# Model Selection & Evaluation
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import LinearSVC
from xgboost import XGBClassifier

In [ ]:
# Deep Learning
from keras.models import Sequential
from keras.layers import Embedding, Conv1D, MaxPooling1D, Flatten, Dense, Dropout
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences


In [ ]:
# Viz
import matplotlib.pyplot as plt
import seaborn as sns

טעינת דאטה

In [ ]:
# דאטה רגיל
df_model = pd.read_csv("data_final.csv")

In [ ]:
df_model['FullText'] = df_model['FullText'].fillna('')


# Bag of Words

זו אחת מהשיטות הכי בסיסיות ב־NLP לייצוג טקסט:

כל טקסט הופך לרשימה של ספירת מילים – בלי קשר לסדר שלהן.

In [ ]:
df_bow = df_model.copy()

In [ ]:
# המרת כל הדאטה ל-Bag of Words (CountVectorizer)
vectorizer = CountVectorizer(max_features=10000)
X_bow = vectorizer.fit_transform(df_bow['FullText'])
y = df_bow['buzz']

In [ ]:
# פיצול ל-Train/Test
X_train_bow, X_test_bow, y_train, y_test = train_test_split(X_bow, y, test_size=0.3, random_state=42, stratify=y)


* Naive Bayes

In [ ]:
# יצירת ואימון המודל
nb = MultinomialNB()
nb.fit(X_train_bow, y_train)

# חיזוי
y_pred_nb = nb.predict(X_test_bow)

# דוחות
print("Accuracy:", accuracy_score(y_test, y_pred_nb))

print("=== Multinomial Naive Bayes על Bag of Words ===")
print(classification_report(y_test, y_pred_nb))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_nb))

Accuracy: 0.6893744644387317
=== Multinomial Naive Bayes על Bag of Words ===
              precision    recall  f1-score   support

           0       0.72      0.56      0.63      3328
           1       0.67      0.80      0.73      3674

    accuracy                           0.69      7002
   macro avg       0.70      0.68      0.68      7002
weighted avg       0.69      0.69      0.68      7002

Confusion Matrix:
 [[1878 1450]
 [ 725 2949]]


*  Random Forest

In [ ]:
# יצירת ואימון המודל
rf = RandomForestClassifier(random_state=42, n_estimators=100)
rf.fit(X_train_bow, y_train)

# חיזוי
y_pred_rf = rf.predict(X_test_bow)

# דוחות
print("Accuracy:", accuracy_score(y_test, y_pred_rf))

print("=== Random Forest על Bag of Words ===")
print(classification_report(y_test, y_pred_rf))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))

Accuracy: 0.6976578120536989
=== Random Forest על Bag of Words ===
              precision    recall  f1-score   support

           0       0.65      0.77      0.71      3328
           1       0.75      0.63      0.69      3674

    accuracy                           0.70      7002
   macro avg       0.70      0.70      0.70      7002
weighted avg       0.71      0.70      0.70      7002

Confusion Matrix:
 [[2563  765]
 [1352 2322]]


* XGBoost

In [ ]:
# יצירת ואימון המודל
xgb = XGBClassifier(
    random_state=42,
    use_label_encoder=False,
    eval_metric='logloss',
    max_depth=5,
    n_estimators=100
)
xgb.fit(X_train_bow, y_train)

# חיזוי
y_pred_xgb = xgb.predict(X_test_bow)

# דוחות
print("Accuracy:", accuracy_score(y_test, y_pred_xgb))

print("=== XGBoost על Bag of Words ===")
print(classification_report(y_test, y_pred_xgb))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_xgb))

/usr/local/lib/python3.11/dist-packages/xgboost/training.py:183: UserWarning: [07:54:49] WARNING: /workspace/src/learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


Accuracy: 0.6925164238788918
=== XGBoost על Bag of Words ===
              precision    recall  f1-score   support

           0       0.75      0.52      0.62      3328
           1       0.66      0.85      0.74      3674

    accuracy                           0.69      7002
   macro avg       0.71      0.68      0.68      7002
weighted avg       0.71      0.69      0.68      7002

Confusion Matrix:
 [[1743 1585]
 [ 568 3106]]


#  TF-IDF (Term Frequency – Inverse Document Frequency)


נותנת משקל גבוה למילים חשובות שמופיעות הרבה במסמך אבל מעט במסמכים אחרים.

היא מורכבת משני שלבים:
TF – כמה פעמים מילה מופיעה בטקסט (כמו BoW).

IDF – מה הופך אותה לנדירה. אם מילה מופיעה כמעט בכל הטקסטים, המשקל שלה ↓.

In [ ]:
df_tfidf = df_model.copy()

In [ ]:
# המרת כל הדאטה ל-TF-IDF
tfidf_vectorizer = TfidfVectorizer(max_features=10000)
X_tfidf = tfidf_vectorizer.fit_transform(df_tfidf['FullText'])
y = df_tfidf['buzz']


In [ ]:
# פיצול ל-Train/Test
X_train_tfidf, X_test_tfidf, y_train, y_test = train_test_split(X_tfidf, y, test_size=0.35, random_state=42, stratify=y)

* Random Forest

In [ ]:
# יצירת ואימון המודל
rf = RandomForestClassifier(random_state=42, n_estimators=100)
rf.fit(X_train_tfidf, y_train)

# חיזוי
y_pred_rf = rf.predict(X_test_tfidf)

# דוחות ביצועים
print("Accuracy:", accuracy_score(y_test, y_pred_rf))

print("=== Random Forest על TF-IDF ===")
print(classification_report(y_test, y_pred_rf))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))

Accuracy: 0.6966580976863753
=== Random Forest על TF-IDF ===
              precision    recall  f1-score   support

           0       0.67      0.72      0.69      3883
           1       0.73      0.67      0.70      4286

    accuracy                           0.70      8169
   macro avg       0.70      0.70      0.70      8169
weighted avg       0.70      0.70      0.70      8169

Confusion Matrix:
 [[2808 1075]
 [1403 2883]]


* XGBoost

In [ ]:

# יצירת ואימון המודל
xgb = XGBClassifier(
    random_state=42,
    use_label_encoder=False,
    eval_metric='logloss',
    max_depth=5,
    n_estimators=100
)
xgb.fit(X_train_tfidf, y_train)

# חיזוי
y_pred_xgb = xgb.predict(X_test_tfidf)

# דוחות ביצועים
print("Accuracy:", accuracy_score(y_test, y_pred_xgb))

print("=== XGBoost על TF-IDF ===")
print(classification_report(y_test, y_pred_xgb))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_xgb))

/usr/local/lib/python3.11/dist-packages/xgboost/training.py:183: UserWarning: [07:55:43] WARNING: /workspace/src/learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


Accuracy: 0.696290855673889
=== XGBoost על TF-IDF ===
              precision    recall  f1-score   support

           0       0.74      0.56      0.64      3883
           1       0.67      0.82      0.74      4286

    accuracy                           0.70      8169
   macro avg       0.71      0.69      0.69      8169
weighted avg       0.70      0.70      0.69      8169

Confusion Matrix:
 [[2172 1711]
 [ 770 3516]]


* Naive Bayes

In [ ]:
# יצירת ואימון המודל
nb = MultinomialNB()
nb.fit(X_train_tfidf, y_train)

# חיזוי
y_pred_nb = nb.predict(X_test_tfidf)

# דוחות ביצועים
print("Accuracy:", accuracy_score(y_test, y_pred_nb))

print("=== Multinomial Naive Bayes על TF-IDF ===")
print(classification_report(y_test, y_pred_nb))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_nb))

Accuracy: 0.6932305055698372
=== Multinomial Naive Bayes על TF-IDF ===
              precision    recall  f1-score   support

           0       0.69      0.65      0.67      3883
           1       0.70      0.73      0.71      4286

    accuracy                           0.69      8169
   macro avg       0.69      0.69      0.69      8169
weighted avg       0.69      0.69      0.69      8169

Confusion Matrix:
 [[2528 1355]
 [1151 3135]]


# Word2Vec

Word2Vec זו שיטה מתקדמת לייצוג טקסטים כוקטורים (embeddings) על בסיס משמעות.
היא שונה מ-Bag of Words/TF-IDF כי היא "מבינה" דמיון סמנטי בין מילים (king ≈ queen, man ≈ woman).

In [ ]:
df_Word2Vec = df_model.copy()

In [ ]:
# פיצול טקסטים לרשימות מילים (Tokenization)
docs = df_Word2Vec['FullText'].astype(str).apply(lambda x: x.split())

 אימון מודל Word2Vec על כל הקורפוס

In [ ]:
w2v_model = Word2Vec(
    sentences=docs,
    vector_size=100,   # אפשר גם 200/300
    window=5,
    min_count=5,
    workers=4,
    sg=1,              # 1=Skip-gram, 0=CBOW
    seed=42
)


קבלת embedding לפוסט שלם

In [ ]:
def get_post_vector(tokens, model):
    # לוקח רק מילים שנמצאות בווקאבולרי של המודל
    vectors = [model.wv[word] for word in tokens if word in model.wv]
    if len(vectors) > 0:
        return np.mean(vectors, axis=0)
    else:
        return np.zeros(model.vector_size)

df_Word2Vec['post_vector'] = docs.apply(lambda tokens: get_post_vector(tokens, w2v_model))


הכנה למודלים

In [ ]:
# יצירת מטריצה מהוקטורים
post_vecs = np.vstack(df_Word2Vec['post_vector'].values)


פיצול Train/Test

In [ ]:
X = post_vecs
y = df_Word2Vec['buzz']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.35, random_state=42, stratify=y)


* Random Forest

In [ ]:
rf = RandomForestClassifier(random_state=42, n_estimators=100)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred_rf))

print("=== Random Forest על Word2Vec ===")
print(classification_report(y_test, y_pred_rf))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))

Accuracy: 0.6948218876239441
=== Random Forest על Word2Vec ===
              precision    recall  f1-score   support

           0       0.70      0.63      0.66      3883
           1       0.69      0.75      0.72      4286

    accuracy                           0.69      8169
   macro avg       0.70      0.69      0.69      8169
weighted avg       0.70      0.69      0.69      8169

Confusion Matrix:
 [[2444 1439]
 [1054 3232]]


* XGBoost

In [ ]:
xgb = XGBClassifier(
    random_state=42,
    use_label_encoder=False,
    eval_metric='logloss',
    max_depth=5,
    n_estimators=100
)
xgb.fit(X_train, y_train)
y_pred_xgb = xgb.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred_xgb))

print("=== XGBoost על Word2Vec ===")
print(classification_report(y_test, y_pred_xgb))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_xgb))

/usr/local/lib/python3.11/dist-packages/xgboost/training.py:183: UserWarning: [07:58:17] WARNING: /workspace/src/learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


Accuracy: 0.6823356591994124
=== XGBoost על Word2Vec ===
              precision    recall  f1-score   support

           0       0.68      0.64      0.66      3883
           1       0.69      0.72      0.70      4286

    accuracy                           0.68      8169
   macro avg       0.68      0.68      0.68      8169
weighted avg       0.68      0.68      0.68      8169

Confusion Matrix:
 [[2476 1407]
 [1188 3098]]


* Naive Bayes

In [ ]:
nb = GaussianNB()
nb.fit(X_train, y_train)
y_pred_nb = nb.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred_nb))

print("=== Gaussian Naive Bayes על Word2Vec ===")
print(classification_report(y_test, y_pred_nb))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_nb))

Accuracy: 0.6136614028644877
=== Gaussian Naive Bayes על Word2Vec ===
              precision    recall  f1-score   support

           0       0.58      0.68      0.63      3883
           1       0.66      0.55      0.60      4286

    accuracy                           0.61      8169
   macro avg       0.62      0.62      0.61      8169
weighted avg       0.62      0.61      0.61      8169

Confusion Matrix:
 [[2642 1241]
 [1915 2371]]


# התחברות לדרייב ויצירת קשר אמיתי על סמך הדאטה ואפשרות ליצירת חיזוי בזמן אמת וחדש

random forest

In [36]:
# 1) חיבור דרייב (אם כבר מחובר – יתעלם)
from google.colab import drive, files
try:
    drive.mount('/content/drive', force_remount=False)
except Exception as e:
    print("Drive already mounted or different state:", e)

# 2) ייבוא מודולים + דאטה (אם כבר מוגדרים למעלה – זה בסדר)
import os, joblib, math
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier  # ⬅️ במקום LogisticRegression

# חשוב: לוודא שהדאטה טעון
assert "df_model" in globals(), "df_model לא מוגדר – טען את ה-CSV לפני התא הזה."
assert "FullText" in df_model.columns and "buzz" in df_model.columns, "חסרות עמודות FullText/buzz"

# 3) בניית ואימון המודל הסופי (TF-IDF + RandomForest) על כל הדאטה
X_all = df_model["FullText"].fillna("").astype(str)
y_all = df_model["buzz"].astype(int)

final_pipe = Pipeline([
    ("tfidf", TfidfVectorizer(max_features=10000)),
    ("clf",  RandomForestClassifier(random_state=42, n_estimators=100)),  # ⬅️ RF
])
final_pipe.fit(X_all, y_all)

# 4) שמירה לדרייב – עם דחיסה
ART_DIR = "/content/drive/MyDrive/Project_Riddet_YVC/CODE"
os.makedirs(ART_DIR, exist_ok=True)

out_path_legacy = f"{ART_DIR}/pipeline_v1.joblib"   # נשמר בשם ה"ישן"
out_path_rf     = f"{ART_DIR}/pipeline_rf.joblib"   # שם ברור נוסף

# ⬅️ compress=3 (אפשר לעלות ל-5/9 אם עדיין גדול)
joblib.dump(final_pipe, out_path_legacy, compress=3)
joblib.dump(final_pipe, out_path_rf, compress=3)

# 5) וידוא/גדלים
print("✅ pipeline_v1.joblib:", math.ceil(os.path.getsize(out_path_legacy)/1024/1024), "MB")
print("✅ pipeline_rf.joblib:", math.ceil(os.path.getsize(out_path_rf)/1024/1024), "MB")
!ls -lah "/content/drive/MyDrive/Project_Riddet_YVC/CODE"

assert os.path.isfile(out_path_legacy), f"לא נמצא קובץ אחרי שמירה: {out_path_legacy}"
assert os.path.isfile(out_path_rf),     f"לא נמצא קובץ אחרי שמירה: {out_path_rf}"

# 6) שמירה גם ב-/content (עם דחיסה) והורדה למחשב
local_path = "/content/pipeline_v1.joblib"
joblib.dump(final_pipe, local_path, compress=3)  # ⬅️ היה חסר compress
print("✅ נשמר: /content/pipeline_v1.joblib")

from google.colab import files
files.download(local_path)


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
✅ pipeline_v1.joblib: 24 MB
✅ pipeline_rf.joblib: 24 MB
total 48M
-rw------- 1 root root 7.7K Aug 16 18:55  cleaning_data-3.ipynb
-rw------- 1 root root 3.2K Aug 16 18:36  create_buzz_target-2.ipynb
-rw------- 1 root root 271K Jun 13 14:08 'data collection-1.ipynb'
-rw------- 1 root root  35K Aug 19 08:17  modilllng_text-5.ipynb
-rw------- 1 root root  24M Aug 19 08:19  pipeline_rf.joblib
-rw------- 1 root root  24M Aug 19 08:19  pipeline_v1.joblib
✅ נשמר: /content/pipeline_v1.joblib


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [37]:
# בדיקת חיזוי מהיר
def predict_once(text):
    p = int(final_pipe.predict([text])[0])
    proba = float(final_pipe.predict_proba([text])[0, 1])
    return p, round(proba, 4)

print(predict_once("This post will explode today!"))

(1, 0.6439)
